// Code generated by mockery v2.10.0. DO NOT EDIT.

package mock

import (
	entity "github.com/sbrunettajr/clean-architecture-api/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// ItemRepo is an autogenerated mock type for the ItemRepo type
type ItemRepo struct {
	mock.Mock
}

// AddItem provides a mock function with given fields: _a0
func (_m *ItemRepo) AddItem(_a0 entity.Item) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Item) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetItems provides a mock function with given fields:
func (_m *ItemRepo) GetItems() ([]entity.Item, error) {
	ret := _m.Called()

	var r0 []entity.Item
	if rf, ok := ret.Get(0).(func() []entity.Item); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
